export const NUMS = [
	{ cls: 'btn orange plus', smb: '+' },
	{ cls: 'btn minus orange', smb: '-' },
	{ cls: 'btn equal orange', smb: '=' },
	{ cls: 'btn seven', smb: '7' },
	{ cls: 'btn eight', smb: '8' },
	{ cls: 'btn nine', smb: '9' },
	{ cls: 'btn four', smb: '4' },
	{ cls: 'btn five', smb: '5' },
	{ cls: 'btn six', smb: '6' },
	{ cls: 'btn one', smb: '1' },
	{ cls: 'btn two', smb: '2' },
	{ cls: 'btn three', smb: '3' },
	{ cls: 'btn zero', smb: '0' },
	{ cls: 'btn clear grey', smb: 'C' },
];
